# Generated by Django 5.2 on 2025-05-28 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('host_email', models.EmailField(help_text='Email address of the host', max_length=254)),
                ('attendees', models.JSONField(help_text='List of attendee email addresses')),
                ('attendee_responses', models.JSONField(default=dict, help_text="Dictionary of attendee responses: {email: {'status': status, 'response_time': timestamp, 'tenant_id': tenant_id, 'chat_id': chat_id}}")),
                ('candidate_times', models.JSONField(help_text='List of candidate time slots')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting'), ('done', 'Done'), ('failed', 'Failed')], default='pending', help_text='Current status of the scheduling process', max_length=10)),
                ('current_try', models.IntegerField(default=0, help_text='Current attempt number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('selected_time', models.JSONField(blank=True, null=True)),
                ('time_zone', models.CharField(default='UTC', help_text='Time zone of the meeting', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('task', models.CharField(max_length=255)),
                ('owner_id', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_name', models.CharField(max_length=255)),
                ('teams_group_id', models.CharField(max_length=255)),
                ('teams_group_name', models.CharField(max_length=255)),
                ('field_address', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('msg_id', models.JSONField(default=list)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
    ]
